name = "srdhpay-api"
main = "workers/src/index.js"
# ให้ใช้ compatibility_date ที่ใหม่ที่สุด ณ วันที่คุณ deploy
# ปัจจุบันคือ 2024-03-20 ถ้าเกิด error ให้ลองไปดูค่าล่าสุดที่ Cloudflare Dashboard -> Workers & Pages -> Overview -> Worker Templates -> Deploy a Worker -> สร้าง Worker ใหม่ -> ลองดูค่า compatibility_date ในไฟล์ wrangler.toml ตัวอย่าง
compatibility_date = "2024-03-20" 

# กำหนดให้ Worker ทำงานที่ path /api/*
# ตอนนี้เรายังไม่รู้ Domain จริง ให้ใช้ wildcard (*) ไปก่อน
# เดี๋ยวเราจะมาเปลี่ยนทีหลัง เมื่อ Cloudflare Pages สร้าง domain ให้แล้ว
# route = { pattern = "*srdhpay.pages.dev/api/*", zone_name = "srdhpay.pages.dev" }
# เพื่อความง่ายสำหรับเริ่มต้น ให้คอมเมนต์ route ออกไปก่อน แล้วไปใช้ custom domain ใน Cloudflare Dashboard แทน (ง่ายกว่าและไม่ต้องเปลี่ยน code)

# เชื่อมต่อระบบฐานข้อมูล D1
[[d1_databases]]
binding = "DB" # ชื่อตัวแปรที่จะเรียกใช้ใน Worker (env.DB)
database_name = "srdhpay_db"
database_id = "26443676-5af5-4dfe-ad5a-f97ce7862fa4"
